# Generated by Django 3.0.5 on 2020-05-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justuser',
            name='college',
            field=models.CharField(max_length=100, verbose_name='College/Organization'),
        ),
    ]
